### ISSUE TITLE
Connect Error

### ISSUE THREAD

**Issue by SmileWHC** [So-Cool/myslideslive#8] opened 2023-10-05 03:40 UTC
Traceback (most recent call last):                                                                                                                                                         
  File "/home/wanghaochen/anaconda3/envs/video_doc/lib/python3.9/site-packages/urllib3/connectionpool.py", line 776, in urlopen                                                            
    self._prepare_proxy(conn)  
  File "/home/wanghaochen/anaconda3/envs/video_doc/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1041, in _prepare_proxy
    conn.connect()                                                                           
  File "/home/wanghaochen/anaconda3/envs/video_doc/lib/python3.9/site-packages/urllib3/connection.py", line 642, in connect             
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(             
  File "/home/wanghaochen/anaconda3/envs/video_doc/lib/python3.9/site-packages/urllib3/connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(         
  File "/home/wanghaochen/anaconda3/envs/video_doc/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/home/wanghaochen/anaconda3/envs/video_doc/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/wanghaochen/anaconda3/envs/video_doc/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/wanghaochen/anaconda3/envs/video_doc/lib/python3.9/ssl.py", line 1074, in _create
    self.do_handshake()
  File "/home/wanghaochen/anaconda3/envs/video_doc/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer
How to fix it, I change the header and proxy

**Comment by So-Cool** [comment] 2023-11-06 21:10
I'm closing this issue as I cannot reproduce the error. @SmileWHC, could you please provide a series of steps to reproduce this error?

**Closed as completed by So-Cool** 2023-11-06 21:10 UTC
